### ISSUE TITLE
TypeError: call_action() got an unexpected keyword argument 'requests_kwargs'

### ISSUE THREAD

**Issue by RabiaSajjad** [ckan/ckanapi#146]
Load command <code>ckanapi load organizations -I transitional_orgs.jsonl -c settings.ini</code> resulted in the following error:

```
Traceback (most recent call last):
  File "/opt/tbs/ckan/venv/bin/ckanapi", line 11, in <module>
    load_entry_point('ckanapi', 'console_scripts', 'ckanapi')()
  File "/opt/tbs/ckan/portal/ckanapi/ckanapi/cli/main.py", line 104, in main
    return _switch_to_paster(arguments)
  File "/opt/tbs/ckan/portal/ckanapi/ckanapi/cli/main.py", line 152, in _switch_to_paster
    sys.exit(load_entry_point('PasteScript', 'console_scripts', 'paster')())
  File "/opt/tbs/ckan/venv/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/opt/tbs/ckan/venv/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/opt/tbs/ckan/venv/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/opt/tbs/ckan/portal/ckanapi/ckanapi/cli/paster.py", line 29, in command
    return main.main(running_with_paster=True)
  File "/opt/tbs/ckan/portal/ckanapi/ckanapi/cli/main.py", line 136, in main
    return load_things(ckan, thing[0], arguments)
  File "/opt/tbs/ckan/portal/ckanapi/ckanapi/cli/load.py", line 47, in load_things
    return load_things_worker(ckan, thing, arguments)
  File "/opt/tbs/ckan/portal/ckanapi/ckanapi/cli/load.py", line 184, in load_things_worker
    requests_kwargs=requests_kwargs)
TypeError: call_action() got an unexpected keyword argument 'requests_kwargs'
```

**Comment by wardi** [comment]
looks like this was caused by a3fd5ba2 not expecting a LocalCKAN instance
